# Generated by Django 5.1.4 on 2025-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
