# Generated by Django 5.1.4 on 2025-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
